spring:
  application:
    name: eureka-ha
---
server:
  port: 8761
spring:
  profiles: weiyi1
eureka:
  instance:
    hostname: weiyi1
  client:
    serviceUrl:
      defaultZone: http://weiyi2:8762/eureka/,http://weiyi3:8763/eureka/
---
server:
  port: 8762
spring:
  profiles: weiyi2
eureka:
  instance:
    hostname: weiyi2
  client:
    serviceUrl:
      defaultZone: http://weiyi1:8761/eureka/,http://weiyi3:8763/eureka/
---
server:
  port: 8763
spring:
  profiles: weiyi3
eureka:
  instance:
    hostname: weiyi3
  client:
    serviceUrl:
      defaultZone: http://weiyi1:8761/eureka/,http://weiyi2:8762/eureka/