server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: weiyi2
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://weiyi1:8001/eureka/