server:
  port: 8001
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: weiyi1
  client:
    #register-with-eureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://weiyi2:8002/eureka/